// workforce-manager-react/src/components/Header.tsx
import { Link } from "react-router-dom";
import IdentityHeader from "./IdentityHeader";

const Header = () =>
{
    return (
        <header>
            <nav className="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div className="container">
                    <Link to="/" className="navbar-brand text-bold">App |</Link>

                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>

                    <div className="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul className="navbar-nav flex-grow-1">
                            <li className="nav-item">
                                <Link to="assignments" className="nav-link text-white">Assignments</Link>
                            </li>
                        </ul>
                    </div>

                    <ul className="navbar-nav">
                        <IdentityHeader />
                    </ul>
                </div>
            </nav>
        </header>
    );
}

export default Header;

// workforce-manager-vue/src/components/Header.vue
<template>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <RouterLink to="/" class="navbar-brand text-bold">App |</RouterLink>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul v-if="identityStore.JWTResponse" class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <RouterLink to="/orders" class="nav-link text-white">Orders</RouterLink>
                        </li>

                        <li class="nav-item">
                            <RouterLink to="/assignments" class="nav-link text-white">Assignments</RouterLink>
                        </li>

                        <li class="nav-item">
                            <RouterLink to="/clients" class="nav-link text-white">Clients</RouterLink>
                        </li>
                    </ul>
                </div>

                <ul class="navbar-nav">
                    <IdentityHeader />
                </ul>
            </div>
        </nav>
    </header>
</template>

<script setup lang="ts">
import { useIdentityStore } from '@/stores/identity'
import IdentityHeader from '@/components/IdentityHeader.vue';

const identityStore = useIdentityStore();
</script>
